### ISSUE TITLE
Crash running hyperglot-validate

### ISSUE THREAD

**Issue by jcrippen** [rosettatype/hyperglot#145]
hyperglot-validate crashes with a simple input file. This is the file, with the filename `tli.yaml`:

```
tli:
  orthographies:
  - base: a á c d e é g g̱ h i í j k ḵ l m n o ó s t u ú w x x̱ y ÿ z ʼ
    autonym: Lingít
    script: Latin
    status: primary
  name: Tlingit
  speakers: 100
  status: living
  validity: verified
```

The crash report is:

```

No color = FYI
Green = FYI, but worth reviewing
Yellow = Might need fixing
Red = Requires fixing

Loading iso-639-3.yaml for names and macro language checks
YAML file structure ok and can be read
Traceback (most recent call last):
  File "/Users/james/Library/Python/3.11/lib/python/site-packages/yaml/reader.py", line 156, in update
    data, converted = self.raw_decode(self.raw_buffer,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 17: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james/Library/Python/3.11/bin/hyperglot-validate", line 33, in <module>
    sys.exit(load_entry_point('hyperglot', 'console_scripts', 'hyperglot-validate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/validate.py", line 349, in validate
    Langs = check_yaml()
            ^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/validate.py", line 40, in check_yaml
    return Languages(validity=VALIDITYLEVELS[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/languages.py", line 81, in __init__
    data = yaml.load(f, Loader=yaml.Loader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Library/Python/3.11/lib/python/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/Users/james/Library/Python/3.11/lib/python/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/Users/james/Library/Python/3.11/lib/python/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/Users/james/Library/Python/3.11/lib/python/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/Users/james/Library/Python/3.11/lib/python/site-packages/yaml/reader.py", line 164, in update
    raise ReaderError(self.name, position, character,
yaml.reader.ReaderError: unacceptable character #x00ac: invalid start byte
  in "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/data/.tli.yaml.swp", position 17
```

**Comment by kontur** [comment]
Are you trying to add the content for `tli.yaml` as what you posted:

```
tli:
  orthographies:
  - base: a á c d e é g g̱ h i í j k ḵ l m n o ó s t u ú w x x̱ y ÿ z ʼ
    autonym: Lingít
    script: Latin
    status: primary
  name: Tlingit
  speakers: 100
  status: living
  validity: verified
```

or like this (without the iso):

```
orthographies:
  - base: a á c d e é g g̱ h i í j k ḵ l m n o ó s t u ú w x x̱ y ÿ z ʼ
    autonym: Lingít
    script: Latin
    status: primary
name: Tlingit
speakers: 100
status: living
validity: verified
```

The later is the correct way and validates fine when I try on the latest `dev`; the iso is implied in the file name and does not need to be repeated in the language data itself.

Please let me know if this is working for you or if the issue persists.

As a side question and because we've faced this issue with several orthographies... the `ʼ` in the orthography, would you say that `U+02BC` is the _ideal_ encoding, but in real life use you might encounter quotation marks (e.g. `U+2019`) or plain apostrophe (e.g. `U+0027`)  as well? We're trying to come up with a way to encode the proper/preferred way, but also there seems to be quite some variance in the actual use of those characters, and thus the font validation we are performing might yield unexpected results.

Thanks for using `hyperglot-validate` when inputting new data ⭐ 

P.S. In so far as possible add a `source` list for new data.

**Comment by MrBrezina** [comment]
@kontur I think there are misleading (old) instructions in the `README_database.md`. I will update it.

**Comment by jcrippen** [comment]
> `.tli.yaml.swp`

Oho, good catch right there! I didn’t see that with all the other stuff in the backtrace.

I created a file `foo` (just `foo` not `foo.yaml`) and put some random text in it. Running `hyperglot-validate` on dev now works without crashing. So the new check for yaml files is working correctly.

Running `hyperglot-validate` on master still crashes as before.

Actually there’s some nuance which is interesting. My editor dropped a `.swp` dotfile which was causing the original crash. With that `.swp` file removed and the `foo` file still in place there is a different crash message.

```
Traceback (most recent call last):
  File "/Users/james/Library/Python/3.11/bin/hyperglot-validate", line 33, in <module>
    sys.exit(load_entry_point('hyperglot', 'console_scripts', 'hyperglot-validate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/validate.py", line 349, in validate
    Langs = check_yaml()
            ^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/validate.py", line 40, in check_yaml
    return Languages(validity=VALIDITYLEVELS[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/languages.py", line 85, in __init__
    self.inherit_orthographies_from_macrolanguage()
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/languages.py", line 236, in inherit_orthographies_from_macrolanguage
    macrolanguages = {iso: lang for iso,
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/languages.py", line 237, in <dictcomp>
    lang in self.items() if "includes" in lang}
                            ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

This new traceback doesn’t tell us the problem file. So the case with the `.swp` file was lucky in that the offending file was explicitly mentioned. I presume there’s a way to get debug info, but it might be useful to have a `-verbose` flag for `hyperglot-validate` that lists each file as it’s processed.

Just to be thorough, here’s a different crash which gets triggered by a malformed yaml file. I removed the file called `foo` and created a new one called `foo.yaml` containing the text `asdf` and nothing else.

```
Traceback (most recent call last):
  File "/Users/james/Library/Python/3.11/bin/hyperglot-validate", line 33, in <module>
    sys.exit(load_entry_point('hyperglot', 'console_scripts', 'hyperglot-validate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/validate.py", line 349, in validate
    Langs = check_yaml()
            ^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/validate.py", line 40, in check_yaml
    return Languages(validity=VALIDITYLEVELS[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/languages.py", line 91, in __init__
    self.filter_by_validity(validity)
  File "/Users/james/Documents/Mine/hyperglot/lib/hyperglot/languages.py", line 260, in filter_by_validity
    if VALIDITYLEVELS.index(lang["validity"]) >= allowed:
                            ~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

You might want to catch that error somehow by sanity checking the yaml syntax. I don’t know if the parser could generate a more clear warning or not. Or maybe just put a note somewhere in the readme about malformed yaml causing an error like this.

Anyway, the initial bug is fixed in dev and I can start on a pull request for `tli.yaml`.

**Comment by kontur** [comment]
Good, please open a possible PR to the `dev` branch, and thanks for helping debug this issue so other contributors may not have to face the same pitfall, if we can help it 👍 

I agree encountering malformed yaml should at the very least output the offending file. Right now it's just a blanket catch all for the yaml parser choking, so that's not very useful. I'll leave this issue open until we have better yaml error catch implemented.
