### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by chrissimpkins** [rosettatype/hyperglot#165]
This error began showing up in the hyperglot GitHub Action CI tests on the Roboto regular weight static font in recent weeks.  Happens in the Linux (Ubuntu) runner environment.  Example run where the error is reported https://github.com/f-actions/hyperglot/actions/runs/8142146443/job/22251041867?pr=128

```
/opt/hostedtoolcache/Python/3.8.18/x64/bin/hyperglot /home/runner/work/hyperglot/hyperglot/tests/fonts/Roboto-Regular.ttf
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/hyperglot", line 5, in <module>
    from hyperglot.cli import cli
  File "/opt/hostedtoolcache/Python/3.8.18/x[64](https://github.com/f-actions/hyperglot/actions/runs/8142146443/job/22251041867?pr=128#step:5:65)/lib/python3.8/site-packages/hyperglot/cli.py", line 20, in <module>
    from hyperglot.language import Language
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/hyperglot/language.py", line 8, in <module>
    from hyperglot.orthography import Orthography
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/hyperglot/orthography.py", line 5, in <module>
    from hyperglot.shaper import Shaper
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/hyperglot/shaper.py", line 13, in <module>
    class Shaper:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/hyperglot/shaper.py", line [71](https://github.com/f-actions/hyperglot/actions/runs/8142146443/job/22251041867?pr=128#step:5:72), in Shaper
    def names_for_codepoints(self, codepoints: Iterable[int]) -> List:
TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by kontur** [comment]
Thanks for reporting, and sorry this slipped past my inbox unnoticed. 0.6.2 should fix this. The cause was my mistaking  `collections.Iterable` for `typing.Iterable` for the type hints, which seems to have tripped up python 3.8.x specifically. Good reminder to run the tests for all supported python versions!

**Comment by chrissimpkins** [comment]
Thank you!
