### ISSUE TITLE
Arg to define glyphset without checking an existing font

### ISSUE THREAD

**Issue by RosaWagner** [rosettatype/hyperglot#86]
It would be nice to create/define glyph sets from number of speakers or orthography status.
For example; listing glyphs necessary to support languages > 20000 speakers

**Comment by kontur** [comment]
For the time being I'd prefer to keep the CLI for working on font files so as to not muddy its purpose. For charset building you could use the library in a script, for example:

```
from hyperglot.languages import Languages
from hyperglot.language import Language, Orthography

glyphs = []
for iso, info in Languages().items():
    lang = Language(info, iso)

    if "speakers" not in lang or lang["speakers"] < 20000: 
        continue

    orth = lang.get_orthography()
    if not orth:
        continue

    orth = Orthography(lang.get_orthography())
    glyphs.extend(orth.base_chars)
    glyphs.extend(orth.required_base_marks)

sorted(set(glyphs))
```

You may look at the constructor options for `Languages` (particularly validity level)  and the `Orthography` attributes  you are interested in (e.g. ignore particular scripts entirely). I know there is a couple of quirks with these objects, but a lot of this is done for augmenting, validating and decomposing the yaml data into actual codepoints. For example, no speaker count in the data is information as such, as is no orthography being given.

For use of the library we should add more documentation in form of concrete "How do I..." examples like this 👍

**Comment by iandoug** [comment]
Similar: given a language (/ code), print out characters in language. Assumes terminal is using font with appropriate glyphs.

Else can just browse the hyperglot.yaml file :-)

Thanks, Ian

**Comment by kontur** [comment]
> Similar: given a language (/ code), print out characters in language. Assumes terminal is using font with appropriate glyphs.

One of the last updates introduced a feature like this. It's split from the main `hyperglot` command, use for example `hyperglot-data eng` or `hyperglot-data Suomi` — it will show info by iso code or attempt to find the language by name.

**Comment by frankrolf** [comment]
I was looking for documentation on how to use Hyperglot to extract characters for a given language (basically, what’s visible on https://hyperglot.rosettatype.com). [This](https://github.com/rosettatype/hyperglot/issues/86#issuecomment-1167015295) was helpful – however, the API seems to have changed:

```
from hyperglot.languages import Languages
from hyperglot.language import Language

glyphs = []
for iso, info in Languages().items():
    lang = Language(info, iso)
    print(lang)

```
```
Traceback (most recent call last):
  File "/Users/fg/Desktop/hyper_test.py", line 6, in <module>
    lang = Language(info, iso)
  File "site-packages/hyperglot/language.py", line 56, in __init__
    data[key] = default
TypeError: 'str' object does not support item assignment
```

it seems that the `info` is no longer needed – what worked is this:
```
from hyperglot.languages import Languages
from hyperglot.language import Language

glyphs = []
for iso, info in Languages().items():
    lang = Language(iso)
```

**Comment by kontur** [comment]
Yes, this is correct. We wanted to make it more easy (and efficient) to interact with the data, so you can simply `Language(xxx)`. This got mentioned in the release notes, but of course individual comments/issues etc. are hard to keep up to date. A more comprehensive "how to" would be valuable, I agree.
